// <auto-generated />
using System;
using Api_WildOasis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WildOasis.Infrastructure.Migrations
{
    [DbContext(typeof(WildOasisContext))]
    partial class WildOasisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_WildOasis.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("CabinId")
                        .HasColumnType("int")
                        .HasColumnName("cabinId");

                    b.Property<double>("CabinPrice")
                        .HasColumnType("float")
                        .HasColumnName("cabinPrice");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("endDate");

                    b.Property<double>("ExtrasPrice")
                        .HasColumnType("float")
                        .HasColumnName("extrasPrice");

                    b.Property<bool>("HasBreakfast")
                        .HasColumnType("bit")
                        .HasColumnName("hasBreakfast");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasColumnName("isPaid");

                    b.Property<short>("NumGuests")
                        .HasColumnType("smallint")
                        .HasColumnName("numGuests");

                    b.Property<short>("NumNights")
                        .HasColumnType("smallint")
                        .HasColumnName("numNights");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("observations")
                        .IsFixedLength();

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("personId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("startDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("status")
                        .IsFixedLength();

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("totalPrice");

                    b.HasKey("BookingId");

                    b.HasIndex("CabinId");

                    b.HasIndex("PersonId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Api_WildOasis.Entities.Cabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<short>("Discount")
                        .HasColumnType("smallint")
                        .HasColumnName("discount");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("image");

                    b.Property<byte>("MaxCapacity")
                        .HasColumnType("tinyint")
                        .HasColumnName("maxCapacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<double>("RegularPrice")
                        .HasColumnType("float")
                        .HasColumnName("regularPrice");

                    b.HasKey("Id");

                    b.ToTable("cabins", (string)null);
                });

            modelBuilder.Entity("Api_WildOasis.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("CountryFlag")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("countryFlag")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("email")
                        .IsFixedLength();

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("fullName")
                        .IsFixedLength();

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("nationalID")
                        .IsFixedLength();

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("nationality")
                        .IsFixedLength();

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Api_WildOasis.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("BreakfastPrice")
                        .HasColumnType("float")
                        .HasColumnName("breakfastPrice");

                    b.Property<short>("MaxBookingLength")
                        .HasColumnType("smallint")
                        .HasColumnName("maxBookingLength");

                    b.Property<short>("MaxGuestsPerBooking")
                        .HasColumnType("smallint")
                        .HasColumnName("maxGuestsPerBooking");

                    b.Property<short>("MinBookingLength")
                        .HasColumnType("smallint")
                        .HasColumnName("minBookingLength");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Api_WildOasis.Entities.Booking", b =>
                {
                    b.HasOne("Api_WildOasis.Entities.Cabin", null)
                        .WithMany()
                        .HasForeignKey("CabinId")
                        .IsRequired();

                    b.HasOne("Api_WildOasis.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
